// content.js — resolve and read files inside the bundled content/ directory.
//
// content/ is generated by scripts/sync-content.mjs and never hand-edited:
// it mirrors ../machine-readable/reference.yaml, ../llms.txt, and the
// ../guide/ tree.

import { readFileSync } from 'node:fs';
import { resolve, sep } from 'node:path';
import { CONTENT_DIR } from './reference.js';

/**
 * Resolve a repo-relative path (e.g. "guide/core/architecture.md") to an
 * absolute path inside content/. Returns null for absolute paths, traversal
 * attempts, and anything that escapes the content directory.
 */
export function resolveContentPath(relativePath) {
  if (typeof relativePath !== 'string' || relativePath.length === 0) return null;
  if (relativePath.includes('\0')) return null;
  if (relativePath.includes('\\')) return null;
  if (resolve(relativePath) === relativePath) return null; // absolute
  const normalized = resolve(CONTENT_DIR, relativePath);
  if (normalized !== CONTENT_DIR && !normalized.startsWith(CONTENT_DIR + sep)) return null;
  return normalized;
}

/**
 * Read one bundled file. Returns its text, or null when the file does not
 * exist (missing page) — callers translate that into a clean tool error.
 */
export function readContentFile(relativePath) {
  const resolved = resolveContentPath(relativePath);
  if (resolved === null) return null;
  try {
    return readFileSync(resolved, 'utf8');
  } catch {
    return null;
  }
}
