#!/usr/bin/env python3
"""generate-llms.py — generate llms.txt and llms-full.txt from guide/ pages.

Fixes the source repo's defect where llms.txt was hand-maintained in three
byte-identical copies: here there is one source (guide/ frontmatter
plus the VERSION file), two generated outputs, and no copies.

Deterministic: output depends only on repo content and VERSION — no
timestamps — so regeneration is byte-identical (idempotent) and the drift
check is exact.

Usage:
  scripts/generate-llms.py           # write llms.txt and llms-full.txt
  scripts/generate-llms.py --check   # fail (exit 1) if committed files drifted
"""

from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "lib"))
import yamlmini  # noqa: E402

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GUIDE_DIR = os.path.join(REPO_ROOT, "guide")
GUIDE_NAME = "Working with Mistral AI Vibe"
GUIDE_BLURB = (
    "Community guide for Mistral AI's Vibe products — Vibe CLI, Vibe Code "
    "desktop, and Vibe Code Web. Voice, page contract, and naming policy: "
    "guide/style-guide.md. Structure and pedagogy adapted from "
    "claude-code-ultimate-guide (CC BY-SA 4.0; see NOTICE.md); all mechanics "
    "independently verified against Vibe."
)


def read_version():
    with open(os.path.join(REPO_ROOT, "VERSION"), encoding="utf-8") as f:
        version = f.read().strip()
    return version


def load_pages():
    """Every .md page under guide/ with its frontmatter and body, sorted by path."""
    pages = []
    for dirpath, dirnames, filenames in os.walk(GUIDE_DIR):
        dirnames.sort()
        for fn in sorted(filenames):
            if not fn.endswith(".md"):
                continue
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, REPO_ROOT)
            with open(full, encoding="utf-8") as f:
                text = f.read()
            fm, body, _ = yamlmini.parse_frontmatter(text, rel)
            for key in ("title", "description"):
                if not fm.get(key):
                    sys.exit(f"FAIL {rel}: frontmatter missing '{key}'")
            pages.append({"rel": rel, "fm": fm, "body": body})
    pages.sort(key=lambda p: p["rel"])
    return pages


def build_llms_txt(pages, version):
    out = [
        f"# {GUIDE_NAME}",
        "",
        f"> {GUIDE_BLURB}",
        "",
        f"Guide version {version}.",
        "",
        "## Guide pages",
        "",
    ]
    for p in pages:
        out.append(f"- [{p['fm']['title']}]({p['rel']}): {p['fm']['description']}")
    out += [
        "",
        "## Machine-readable entry points",
        "",
        "- machine-readable/reference.yaml: generated index of every guide page "
        "(file path, title, description, tags, headings with line numbers)",
        "- machine-readable/schema.md: schema of reference.yaml",
        "",
    ]
    return "\n".join(out)


def build_llms_full(pages, version):
    out = [
        f"# {GUIDE_NAME} — full text",
        "",
        f"Guide version {version}.",
        "Generated by scripts/generate-llms.py from guide/ pages; do not edit "
        "by hand. Regenerate with scripts/sync-version.sh.",
        "",
    ]
    for p in pages:
        out += [
            "---",
            "",
            f"## Page: {p['fm']['title']} ({p['rel']})",
            "",
            p["body"].strip("\n"),
            "",
        ]
    return "\n".join(out)


def main():
    check = "--check" in sys.argv[1:]
    version = read_version()
    pages = load_pages()
    artifacts = {
        "llms.txt": build_llms_txt(pages, version),
        "llms-full.txt": build_llms_full(pages, version),
    }

    drift = []
    for name, content in artifacts.items():
        path = os.path.join(REPO_ROOT, name)
        if os.path.exists(path):
            with open(path, encoding="utf-8") as f:
                committed = f.read()
        else:
            committed = None
        if committed != content:
            drift.append(name)
            if not check:
                with open(path, "w", encoding="utf-8") as f:
                    f.write(content)
                print(f"wrote {name}")

    if check:
        if drift:
            for name in drift:
                print(f"FAIL {name}: drifted from guide/ frontmatter; regenerate with "
                      f"scripts/generate-llms.py")
            sys.exit(1)
        print("llms drift check: clean (llms.txt, llms-full.txt up to date)")
    elif not drift:
        print("llms.txt, llms-full.txt already up to date")


if __name__ == "__main__":
    main()
