#!/usr/bin/env python3
"""generate-reference.py — generate machine-readable/reference.yaml.

Emits an index of every guide/ page: file path, title, description, tags
(from frontmatter) and headings with line numbers (from the page body). The
schema is documented in machine-readable/schema.md. Replaces the source
repo's hand-maintained 4K-line reference.yaml: the index is now a
generated artifact with a drift check, so "content nobody indexed is
content nobody can find" is enforced mechanically.

Deterministic: pages sorted by path, no timestamps — regeneration is
byte-identical and the drift check is exact.

Usage:
  scripts/generate-reference.py           # write machine-readable/reference.yaml
  scripts/generate-reference.py --check   # fail (exit 1) if the file drifted
"""

from __future__ import annotations

import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "lib"))
import markdown  # noqa: E402
import yamlmini  # noqa: E402

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GUIDE_DIR = os.path.join(REPO_ROOT, "guide")
OUT_REL = "machine-readable/reference.yaml"


def y(value):
    """Emit a YAML flow scalar via JSON (valid YAML, deterministic quoting)."""
    return json.dumps(value, ensure_ascii=False)


def read_version():
    with open(os.path.join(REPO_ROOT, "VERSION"), encoding="utf-8") as f:
        return f.read().strip()


def load_pages():
    pages = []
    for dirpath, dirnames, filenames in os.walk(GUIDE_DIR):
        dirnames.sort()
        for fn in sorted(filenames):
            if not fn.endswith(".md"):
                continue
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, REPO_ROOT)
            with open(full, encoding="utf-8") as f:
                text = f.read()
            fm, body, offset = yamlmini.parse_frontmatter(text, rel)
            for key in ("title", "description"):
                if not fm.get(key):
                    sys.exit(f"FAIL {rel}: frontmatter missing '{key}'")
            pages.append({
                "rel": rel,
                "fm": fm,
                # heading lines are reported as file line numbers (1-based)
                "headings": [(lvl, txt, line + offset)
                             for lvl, txt, line in markdown.extract_headings(body)],
            })
    pages.sort(key=lambda p: p["rel"])
    return pages


def build_reference(pages, version):
    out = [
        "# Generated by scripts/generate-reference.py from guide/ frontmatter and headings.",
        "# Do not edit by hand. Schema: machine-readable/schema.md.",
        f'version: "{version}"',
        "pages:",
    ]
    for p in pages:
        fm = p["fm"]
        out.append(f"  - path: {y(p['rel'])}")
        out.append(f"    title: {y(fm['title'])}")
        out.append(f"    description: {y(fm['description'])}")
        tags = fm.get("tags") or []
        if not isinstance(tags, list):
            sys.exit(f"FAIL {p['rel']}: 'tags' must be a list")
        out.append("    tags: [" + ", ".join(y(t) for t in tags) + "]")
        out.append("    headings:")
        if not p["headings"]:
            out.append("      []")
        for level, text, line in p["headings"]:
            out.append(f"      - level: {level}")
            out.append(f"        text: {y(text)}")
            out.append(f"        line: {line}")
    return "\n".join(out) + "\n"


def main():
    check = "--check" in sys.argv[1:]
    version = read_version()
    content = build_reference(load_pages(), version)
    path = os.path.join(REPO_ROOT, OUT_REL)

    committed = None
    if os.path.exists(path):
        with open(path, encoding="utf-8") as f:
            committed = f.read()

    if committed != content:
        if check:
            print(f"FAIL {OUT_REL}: drifted from guide/ content; regenerate with "
                  "scripts/generate-reference.py")
            sys.exit(1)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"wrote {OUT_REL}")
    else:
        print(f"{OUT_REL} already up to date" if not check
              else "reference drift check: clean")


if __name__ == "__main__":
    main()
