#!/bin/bash
# sync-version.sh — VERSION is the single source of truth for the guide version.
#
# Adapted from the source repo's VERSION→docs sync chain, simplified:
# every version-bearing artifact in this repo is GENERATED, so syncing means
# regenerating, and the check verifies that each artifact carries the current
# VERSION at its expected marker.
#
# Version-bearing artifacts and their markers:
#   llms.txt                      "Guide version X.Y.Z"
#   llms-full.txt                 "Guide version X.Y.Z"
#   machine-readable/reference.yaml   version: "X.Y.Z"
#   guide/vibe-guide.md           "Guide version X.Y.Z" (generated by
#                                 scripts/generate-monolith.py)
#
# A pre-release suffix is allowed in VERSION (X.Y.Z-dev) for release
# rehearsals and in-flight releases (scripts/release.sh --dry-run); the
# suffix propagates into the generated markers verbatim.
#
# Usage:
#   scripts/sync-version.sh            # fix: regenerate artifacts from VERSION
#   scripts/sync-version.sh --check    # check only; exit 1 on mismatch
#
# Used by: .pre-commit-config.yaml and .github/workflows/ci.yml (check mode).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

if [[ ! -f VERSION ]]; then
  echo "FAIL VERSION file not found" >&2
  exit 1
fi

VERSION="$(tr -d '[:space:]' < VERSION)"
if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?$ ]]; then
  echo "FAIL VERSION is not valid semver: '$VERSION'" >&2
  exit 1
fi

FILES=(llms.txt llms-full.txt machine-readable/reference.yaml guide/vibe-guide.md)

marker() {
  case "$1" in
    machine-readable/reference.yaml) echo "^version: \"$VERSION\"$" ;;
    *) echo "Guide version $VERSION" ;;
  esac
}

check() {
  local errors=0
  echo "=== Version sync (check) — VERSION = $VERSION ==="
  for f in "${FILES[@]}"; do
    if [[ ! -f "$f" ]]; then
      echo "FAIL $f: missing (run scripts/sync-version.sh)"
      errors=$((errors + 1))
    elif grep -qE "$(marker "$f")" "$f"; then
      echo "OK   $f"
    else
      echo "FAIL $f: current version marker not found (expected $VERSION)"
      errors=$((errors + 1))
    fi
  done
  if [[ $errors -gt 0 ]]; then
    echo "Run: scripts/sync-version.sh"
    return 1
  fi
  echo "version sync: clean"
}

if [[ "${1:-}" == "--check" ]]; then
  check
else
  echo "=== Version sync (fix) — regenerating artifacts from VERSION = $VERSION ==="
  # Order matters: the monolith spine is embedded by llms-full.txt (and its
  # headings are indexed by reference.yaml), so it regenerates first.
  python3 scripts/generate-monolith.py
  python3 scripts/generate-reference.py
  python3 scripts/generate-llms.py
  exec scripts/sync-version.sh --check
fi
